Repository CA-G12/jobs-Nada-agha, pull requests merged in 2022-08, with the labels that each got.

#2 build the file structer
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/js/dom.js
  public/js/logic.js
  public/main.css
  src/Controllers/errors.js
  src/Controllers/handelers.js
  src/Controllers/index.js
  src/app.js
  src/index.js
Labels: done

#5 create server
  package-lock.json
  package.json
  src/index.js
Labels: approved

#7 create route file
  public/index.html
  src/index.js
Labels: done

#11 create erver side
  src/index.js
Labels: approved

#14 13 call fetch
  public/index.html
  public/js/dom.js
Labels: done

#15 fix api link and set headers
  src/index.js
Labels: done

#17 edit the file structure and style
  public/index.html
  public/main.css
Labels: approved

#20 crete the search section and styled it
  public/index.html
  public/main.css
Labels: done

#22 create the 404 page
  public/errors/404.html
  public/js/logic.js
  src/index.js
Labels: approved

#24 create content section
  public/index.html
  public/main.css
Labels: done

#27 handle the data returned from the api and pass it to the dom
  public/index.html
  public/js/dom.js
  public/js/logic.js
  public/main.css
Labels: done

#30 add reloder to the page
  public/index.html
  public/js/dom.js
  public/js/logic.js
  public/main.css
Labels: done

#32 fixed the style and add animation
  public/js/dom.js
  public/main.css
Labels: done

#34 write readme file
  README.md
Labels: done

#36 create test
  package.json
  src/index.js
  test.js
Labels: done

#41 create split modules
  src/Controllers/errors.js
  src/Controllers/handelers.js
  src/Controllers/index.js
  src/app.js
  src/index.js
Labels: awating -review
